return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "clangd",
      "codelldb",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "hadolint",
      "haskell-language-server",
      "helm-ls",
      "json-lsp",
      "kube-linter",
      "lua-language-server",
      "markdown-toc",
      "markdownlint",
      "markdownlint-cli2",
      "marksman",
      "pyright",
      "ruff",
      "shellcheck",
      "shfmt",
      "sqlfluff",
      "stylua",
      "taplo",
      "yaml-language-server",
    },
  },
}
